"""empty message

Revision ID: be77e6d71cf
Revises: 55cfad75c353
Create Date: 2016-11-02 19:27:27.663199

"""

# revision identifiers, used by Alembic.
revision = 'be77e6d71cf'
down_revision = '55cfad75c353'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DruhDortu', sa.String(), nullable=False),
    sa.Column('Cena', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_dort'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_dort_Cena', 'dort', ['Cena'], unique=False)
    op.create_index('ix_dort_DruhDortu', 'dort', ['DruhDortu'], unique=False)
    op.drop_table('papir')
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.create_table('papir',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('DruhPapiru', sa.VARCHAR(), nullable=False),
    sa.Column('Cena', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_dort_DruhDortu', table_name='dort')
    op.drop_index('ix_dort_Cena', table_name='dort')
    op.drop_table('dort')
    ### end Alembic commands ###
